### ISSUE TITLE
does not install on raspbian / kernel 5.10.11-v7+

### ISSUE THREAD

**Issue by ycardon** [matrix-io/matrixio-kernel-modules#54]
Hello, after an update to kernel `5.10.11-v7+`, I cannot get the matrixio-kernel-modules to install anymore.

```
sudo apt install matrixio-kernel-modules
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  matrixio-kernel-modules
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/20.9 kB of archives.
After this operation, 116 kB of additional disk space will be used.
Selecting previously unselected package matrixio-kernel-modules.
(Reading database ... 136881 files and directories currently installed.)
Preparing to unpack .../matrixio-kernel-modules_0.2.4_all.deb ...
Unpacking matrixio-kernel-modules (0.2.4) ...
Setting up matrixio-kernel-modules (0.2.4) ...
Loading new matrixio-kernel-modules-0.2.4 DKMS files...
It is likely that 5.10.11-v7+ belongs to a chroot's host
Building for 4.19.75-v7+, 5.10.11+, 5.10.11-v7+, 5.10.11-v7l+ and 5.10.11-v8+
Module build for kernel 4.19.75-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 5.10.11+
Error! Bad return status for module build on kernel: 5.10.11+ (armv7l)
Consult /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/make.log for more information.
dpkg: error processing package matrixio-kernel-modules (--configure):
 installed matrixio-kernel-modules package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 matrixio-kernel-modules
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

and `/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/make.log`

```
DKMS make.log for matrixio-kernel-modules-0.2.4 for kernel 5.10.11+ (armv7l)
Fri Feb  5 15:39:55 CET 2021
make: Entering directory '/usr/src/linux-headers-5.10.11+'
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-core.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-uart.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-everloop.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-codec.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-gpio.o
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:6: error: ‘const struct snd_soc_component_driver’ has no member named ‘ops’; did you mean ‘open’?
     .ops = &matrixio_pcm_ops, .pcm_new = matrixio_pcm_new,
      ^~~
      open
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:12: error: initialization of ‘const char *’ from incompatible pointer type ‘const struct snd_pcm_ops *’ [-Werror=incompatible-pointer-types]
     .ops = &matrixio_pcm_ops, .pcm_new = matrixio_pcm_new,
            ^
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:12: note: (near initialization for ‘matrixio_soc_platform.name’)
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:32: error: ‘const struct snd_soc_component_driver’ has no member named ‘pcm_new’
     .ops = &matrixio_pcm_ops, .pcm_new = matrixio_pcm_new,
                                ^~~~~~~
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:42: error: initialization of ‘const struct snd_kcontrol_new *’ from incompatible pointer type ‘int (*)(struct snd_soc_pcm_runtime *)’ [-Werror=incompatible-pointer-types]
     .ops = &matrixio_pcm_ops, .pcm_new = matrixio_pcm_new,
                                          ^~~~~~~~~~~~~~~~
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:42: note: (near initialization for ‘matrixio_soc_platform.controls’)
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:279: /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.o] Error 1
make[1]: *** Waiting for unfinished jobs....
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:338:6: error: ‘const struct snd_soc_component_driver’ has no member named ‘ops’; did you mean ‘open’?
     .ops = &matrixio_playback_ops,
      ^~~
      open
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:338:12: error: initialization of ‘const char *’ from incompatible pointer type ‘struct snd_pcm_ops *’ [-Werror=incompatible-pointer-types]
     .ops = &matrixio_playback_ops,
            ^
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:338:12: note: (near initialization for ‘matrixio_soc_platform.name’)
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:339:6: error: ‘const struct snd_soc_component_driver’ has no member named ‘pcm_new’
     .pcm_new = matrixio_playback_new,
      ^~~~~~~
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:339:16: error: initialization of ‘const struct snd_kcontrol_new *’ from incompatible pointer type ‘int (*)(struct snd_soc_pcm_runtime *)’ [-Werror=incompatible-pointer-types]
     .pcm_new = matrixio_playback_new,
                ^~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:339:16: note: (near initialization for ‘matrixio_soc_platform.controls’)
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:279: /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.o] Error 1
make: *** [Makefile:1808: /var/lib/dkms/matrixio-kernel-modules/0.2.4/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.10.11+'
```

Building from source give the same errors.

**Comment by HinTak** [comment]
Good you found https://github.com/matrix-io/matrixio-kernel-modules/pull/53 - did you forget the change in /boot/config.txt or did not copy the dtbo along?

**Comment by ycardon** [comment]
I did change `/boot/config.txt` but when I'm `sudo make install` the #53 I get the following warning about `depmod`. I don't know if it's normal or not.

```
sudo make install
make -C /lib/modules/5.10.11-v7+/build M=/home/ycardon/dev/matrixio-kernel-modules/src modules_install
make[1]: Entering directory '/usr/src/linux-headers-5.10.11-v7+'
  INSTALL /home/ycardon/dev/matrixio-kernel-modules/src/matrixio-codec.ko
  INSTALL /home/ycardon/dev/matrixio-kernel-modules/src/matrixio-core.ko
  INSTALL /home/ycardon/dev/matrixio-kernel-modules/src/matrixio-env.ko
  INSTALL /home/ycardon/dev/matrixio-kernel-modules/src/matrixio-everloop.ko
  INSTALL /home/ycardon/dev/matrixio-kernel-modules/src/matrixio-gpio.ko
  INSTALL /home/ycardon/dev/matrixio-kernel-modules/src/matrixio-imu.ko
  INSTALL /home/ycardon/dev/matrixio-kernel-modules/src/matrixio-mic.ko
  INSTALL /home/ycardon/dev/matrixio-kernel-modules/src/matrixio-playback.ko
  INSTALL /home/ycardon/dev/matrixio-kernel-modules/src/matrixio-regmap.ko
  INSTALL /home/ycardon/dev/matrixio-kernel-modules/src/matrixio-uart.ko
  DEPMOD  5.10.11-v7+
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.10.11-v7+'
depmod -A
cp matrixio.dtbo /boot/overlays
```
Your PR was on `5.9` kernel, should it also work on `5.10` (ie. are you using `5.10` and is it working for you) ?

**Comment by HinTak** [comment]
That system.map message is certainly worrying, but the important part is why of_node can't be read, which suggests the dtbo is not loading or not working correctly.

**Comment by sjdevlin** [comment]
I have the same problem.  The make log is:  

DKMS make.log for matrixio-kernel-modules-0.2.4 for kernel 5.10.11+ (armv7l)
Sun 14 Feb 13:26:40 GMT 2021
make: Entering directory '/usr/src/linux-headers-5.10.11+'
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-core.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-uart.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-everloop.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-codec.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-gpio.o
  CC [M]  /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-env.o
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:6: error: 'const struct snd_soc_component_driver' has no member named 'ops'; did you mean 'open'?
     .ops = &matrixio_pcm_ops, .pcm_new = matrixio_pcm_new,
      ^~~
      open
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:12: error: initialization of 'const char *' from incompatible pointer type 'const struct snd_pcm_ops *' [-Werror=incompatible-pointer-types]
     .ops = &matrixio_pcm_ops, .pcm_new = matrixio_pcm_new,
            ^
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:12: note: (near initialization for 'matrixio_soc_platform.name')
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:32: error: 'const struct snd_soc_component_driver' has no member named 'pcm_new'
     .ops = &matrixio_pcm_ops, .pcm_new = matrixio_pcm_new,
                                ^~~~~~~
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:42: error: initialization of 'const struct snd_kcontrol_new *' from incompatible pointer type 'int (*)(struct snd_soc_pcm_runtime *)' [-Werror=incompatible-pointer-types]
     .ops = &matrixio_pcm_ops, .pcm_new = matrixio_pcm_new,
                                          ^~~~~~~~~~~~~~~~
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.c:306:42: note: (near initialization for 'matrixio_soc_platform.controls')
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:279: /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-mic.o] Error 1
make[1]: *** Waiting for unfinished jobs....
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:338:6: error: 'const struct snd_soc_component_driver' has no member named 'ops'; did you mean 'open'?
     .ops = &matrixio_playback_ops,
      ^~~
      open
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:338:12: error: initialization of 'const char *' from incompatible pointer type 'struct snd_pcm_ops *' [-Werror=incompatible-pointer-types]
     .ops = &matrixio_playback_ops,
            ^
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:338:12: note: (near initialization for 'matrixio_soc_platform.name')
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:339:6: error: 'const struct snd_soc_component_driver' has no member named 'pcm_new'
     .pcm_new = matrixio_playback_new,
      ^~~~~~~
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:339:16: error: initialization of 'const struct snd_kcontrol_new *' from incompatible pointer type 'int (*)(struct snd_soc_pcm_runtime *)' [-Werror=incompatible-pointer-types]
     .pcm_new = matrixio_playback_new,
                ^~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.c:339:16: note: (near initialization for 'matrixio_soc_platform.controls')
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:279: /var/lib/dkms/matrixio-kernel-modules/0.2.4/build/matrixio-playback.o] Error 1
make: *** [Makefile:1808: /var/lib/dkms/matrixio-kernel-modules/0.2.4/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.10.11+'

**Comment by mleglise** [comment]
+1    Same issue on a completely fresh install.
Raspbian base install
sudo apt-get update
sudo apt-get upgrade
Install docker
Install Matrix kernel modules
Fails on "sudo apt-get install matrixio-kernel-modules" with exactly the error logs pasted by others above.

@HinTak if it would help you out for me to proceed with attempting to use #53 for additional debugging, I'll gladly do so. I'm proficient with *nix, but a new Matrix user (which is how I have a perfectly fresh install). No concerns about blowing away my install and starting from scratch as many times as needed, especially since I know users that have a fully running system are often averse to doing so.

**Comment by HinTak** [comment]
Is there any message in dmesg after boot and or when doing playing / recording? The most suspect problem is the of_node message at the moment.

**Comment by mleglise** [comment]
@HinTak the of_node message appears twice in dmesg, along with some other bolded messages.
```
[    5.215039] matrixio-everloop: Failed to locate of_node [id: -1]
[    5.291303] matrixio-regmap: Failed to locate of_node [id: -1]
```

I'm moving this convo over to #53 and pasting the entire dmesg output there for you.

**Comment by chiefymuc** [comment]
Not sure if this helps, but with Kernel 5.4 it still works:

```
http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel_1.20201126-1_armhf.deb
rpi_kernel_headers_5-4.deb http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel-headers_1.20201126-1_armhf.deb

Linux matrixpi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
```

**Comment by morlac** [comment]
I have the same compile-issue on archlinux on raspi4.
To me it seems according to the above error-message(s) the struct snd_soc_component_driver has changed in 5.10.

**Comment by mleglise** [comment]
For those that may need more spelled out instructions for moving back to Kernel 5.4 (per @chiefymuc 's suggestion above)
```
curl http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel_1.20201126-1_armhf.deb -o raspberrypi-kernel_1.20201126-1_armhf.deb
sudo dpkg -i raspberrypi-kernel_1.20201126-1_armhf.deb
sudo reboot

curl http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel-headers_1.20201126-1_armhf.deb -o raspberrypi-kernel-headers_1.20201126-1_armhf.deb
sudo dpkg -i raspberrypi-kernel-headers_1.20201126-1_armhf.deb
sudo reboot

sudo apt-get remove matrixio-kernel-modules
sudo apt-get install matrixio-kernel-modules
sudo reboot
```

Is this too many reboots? Maybe. I prefer to do it as a precaution. You're futzing with the kernel after all.

**Comment by Alfred-AdMobilize** [comment]
Hey Everyone, sorry for the delay here.

We are aware of this issue and are still working on a fix. (Kernel land is difficult)

In the mean time you can use our temporary fix to rollback the kernel bellow:

`wget http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel_1.20201126-1_armhf.deb

wget http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel-headers_1.20201126-1_armhf.deb

sudo dpkg -i raspberrypi-kernel-headers_1.20201126-1_armhf.deb  raspberrypi-kernel_1.20201126-1_armhf.deb

sudo reboot

sudo apt install matrixio-kernel-modules

sudo reboot`

Thanks @mleglise for your instructions. :)
